server:
port:9888
servlet:
context-path:/operation
spring:
servlet:
multipart:
max-file-size:50MB
max-request-size:50MB
datasource:
operate:
driver-class-name:com.mysql.cj.jdbc.Driver
jdbc-url:jdbc:mysql://192.168.2.161:3306/zlop?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF8
username:root
password:123456
jpa:
show-sql:true
hibernate:
ddl-auto:update
naming:
physical-strategy:org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
implicit-strategy:org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
properties:
hibernate:
dialect:org.hibernate.dialect.MySQL57Dialect
format_sql:false
use_sql_comments:false
order_inserts:true
order_updates:true
jdbc:
batch_size:500
batch_versioned_data:true
open-in-view:true